name: Distribute Debug Build to Firebase

on:
  workflow_dispatch:

jobs:

  distributeDefaultDebug:
    name: Distribute Debug Version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.x'

      - name: Install bundle
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Create service credentials file
        run: |
          echo "$FIREBASE_CREDENTIALS" > firebase_credentials.json.b64
          base64 -d -i firebase_credentials.json.b64 > AppDistributionConfig/firebase-credentials.json
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.THRONES_FIREBASE_CREDENTIALS }}

      - name: Store CLI Token as environment variable
        run: echo "THRONES_CLI_TOKEN=${{ secrets.THRONES_CLI_TOKEN }}" >> $GITHUB_ENV

      - name: Store Application ID as environment variable
        run: echo "THRONES_APP_ID=${{ secrets.THRONES_APP_ID }}" >> $GITHUB_ENV

      - name: Code Validation
        run: bundle exec fastlane detekt

      - name: Run Unit Tests
        run: bundle exec fastlane unitTest

      - name: Deploy Debug Build to Firebase App Distribution
        run: bundle exec fastlane deployToFirebase